require 'rails_helper'

RSpec.describe Event, type: :model do

  it { should validate_uniqueness_of(:event_id) }

  let(:event) { Event.create_with_session_id('foo') }
  let(:open_tok) { double(generate_token: 'token') }

  it "should set the event_id when created" do
    expect(event.event_id).to be_present
  end
  it "should be 6 alpha numberic uppercase characters" do
    expect(event.event_id).to match /\A[A-Z0-9]{6}\z/
  end
  describe "token" do
    before(:each) do
      stub_const("OPENTOK", open_tok)
    end
    it "should be generated by OPENTOK" do
      expect(open_tok).to receive(:generate_token)
      event.token
    end
    it "should be memoized" do
      expect(open_tok).to receive(:generate_token).once
      event.token
      event.token
    end
  end
end
