# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

# # Initialize an OpenTok Session object
#
# session = TB.initSession(sessionId)
# # Initialize a Publisher, and place it into the element with id="publisher"
# # publisher = TB.initPublisher(apiKey, 'publisher')
# # Attach event handlers
# session.on
#   # sessionConnected: (event) ->
#   #   # Publish the publisher we initialzed earlier (this will trigger 'streamCreated' on other
#   #   # clients)
#   #   session.publish publisher
#   #   return
#   streamCreated: (event) ->
#     # Create a container for a new Subscriber, assign it an id using the streamId, put it inside
#     # the element with id="subscribers"
#     subContainer = document.createElement('div')
#     subContainer.id = 'stream-' + event.stream.streamId
#     document.getElementById('subscribers').appendChild subContainer
#     # Subscribe to the stream that caused this event, put it inside the container we just made
#     session.subscribe event.stream, subContainer
#     return
# # Connect to the Session using the 'apiKey' of the application and a 'token' for permission
# session.connect apiKey, token

# ---
# generated by js2coffee 2.1.0
